# Generated by Django 5.0 on 2024-07-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='month',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('ACTIVE', 'Activa'), ('DESACTIVE', 'Desactivada')], default='PENDING', max_length=50),
        ),
    ]
