# Generated by Django 5.0 on 2024-07-05 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='month',
            new_name='license',
        ),
    ]
