# Generated by Django 5.0 on 2024-07-06 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_remove_client_password_integration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('DESACTIVE', 'Desactivado')], default='ACTIVE', max_length=80)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.client')),
            ],
            options={
                'verbose_name': 'Rostros',
                'verbose_name_plural': 'Rostro',
            },
        ),
    ]
