# Generated by Django 5.0 on 2024-08-05 21:13

import django.db.models.deletion
import recognition.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recognition", "0002_face_face_encoding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="face",
            name="face_encoding",
        ),
        migrations.RemoveField(
            model_name="face",
            name="image",
        ),
        migrations.CreateModel(
            name="FaceTraining",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=recognition.models.face_directory_path,
                        verbose_name="Imagen",
                    ),
                ),
                ("face_encoding", models.TextField(blank=True)),
                (
                    "face",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="recognition.face",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
