# Generated by Django 5.0 on 2024-08-09 14:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0007_remove_client_password_integration_and_more"),
        ("recognition", "0003_remove_face_face_encoding_remove_face_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facetraining",
            name="face",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recognition.face"
            ),
        ),
        migrations.CreateModel(
            name="FacePredict",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("found_face", models.BooleanField(default=False)),
                (
                    "client_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="clients.client",
                    ),
                ),
                (
                    "face",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="recognition.face",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
