# Generated by Django 5.0 on 2024-08-09 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recognition", "0004_alter_facetraining_face_facepredict"),
    ]

    operations = [
        migrations.RenameField(
            model_name="facepredict",
            old_name="client_id",
            new_name="client",
        ),
        migrations.AlterField(
            model_name="facepredict",
            name="face",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="recognition.face",
            ),
        ),
    ]
